# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Working with me"
  url = "#phd"
  weight = 20

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 30

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 40

[[main]]
  name = "Talks"
  url = "#talks"
  weight = 50

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 60

[[main]]
  name = "Teaching & Services"
  url = "#teaching"
  weight = 70

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/cv.pdf"
#    weight = 70
