# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Thomas Pasquier is an Assistant Professor in Computer Science at the University of British Columbia.'
    twitter: 'tfjmp'
  analytics:
    google_analytics: ''
    google_tag_manager: 'GTM-W7M7XP3'
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

footer:
  copyright:
    notice: '&copy; 2017-{year} Thomas Pasquier'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  diagram:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/tfjmp/website'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 0

# Extensions

extensions:
  cms:
    branch: master
    local_backend: false
  isotope:
    # Enable if you use the Portfolio widget or Publication filter
    enable: true
  academicons:
    enable: true
